### ISSUE TITLE
API: OpenScanHub URLs are not in https

### ISSUE THREAD

**Issue by Venefilyn** [openscanhub/openscanhub#305] opened 2024-11-18 12:33 UTC
Since OSH redirects `http` to `https` it feels like an easy oversight when returning the URLs in the API as `http`. Coming from the Packit side I saw that they get `http` URLs.

**Comment by siteshwar** [comment] 2024-11-18 12:46
It is a duplicate of https://github.com/openscanhub/fedora-infra/issues/73, although I have not found time to dig into it yet.

**Closed by siteshwar** 2024-11-18 12:46 UTC
